In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data/ILGA_State_Sponsored_Homophobia_2019_dataset.xlsx', sheet_name='All categories')

In [3]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,CRIMINALISATION,Unnamed: 5,Unnamed: 6,PROTECTION,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,RECOGNITION,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,CONSENSUAL SAME-SEX SEXUAL ACTS,GENDER,MAX PENALTY,PROTECTION AGAINST DISCRIMINATION,NaN,NaN,CRIMINALISATION OF VIOLENCE/DISCRIMINATION,NaN,CTs,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION
1,N,CN,CONTINENT,COUNTRY,Legal?,Gender/s,Years in Prison / Other,Constitutional,Broad Protections,Employment,Hate Crime / Aggr. Circs.,Incitement to Hatred / Violence,Ban on CTs,Marriage,Civil Unions,Joint Adoption,Second Parent Adoption
2,1,1,AFRICA,Algeria,NO,ANY GENDER,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,2,2,AFRICA,Angola,YES,DOES NOT APPLY,DOES NOT APPLY,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
4,3,3,AFRICA,Benin,YES,DOES NOT APPLY,DOES NOT APPLY,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,68,0.352332,UN Member States CRIMINALISE consensual s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NaN,NaN,NaN,NaN,2,0.010363,UN Member States DE FACTO CRIMINALISE con...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NaN,NaN,NaN,123,0.637306,UN Member States DO NOT criminalise conse...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,CRIMINALISATION,Unnamed: 5,Unnamed: 6,PROTECTION,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,RECOGNITION,Unnamed: 14,Unnamed: 15,Unnamed: 16
198,191,12,OCEANIA,Tonga,NO,MALE ONLY,10,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
199,192,13,OCEANIA,Tuvalu,NO,MALE ONLY,14,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
200,193,14,OCEANIA,Vanuatu,YES,DOES NOT APPLY,DOES NOT APPLY,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,52,73,42,40,3,26,27,27,30
202,YES,(1).,"In Palestine, Gaza still criminalises same-sex...",NaN,NaN,NaN,NaN,0.046632,0.26943,0.378238,0.217617,0.207254,0.015544,0.134715,0.139896,0.139896,0.15544
203,NO,NaN,NaN,NaN,NaN,NaN,NaN,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States,UN Member States
204,NaN,(2).,"In Indonesia, several provinces criminalise co...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,44,Criminalise all same-sex sexual acts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,26,Criminalise same-sex sexual acts between MEN only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,NaN,NaN,68,0.352332,UN Member States CRIMINALISE consensual s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NaN,NaN,NaN,NaN,2,0.010363,UN Member States DE FACTO CRIMINALISE con...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,NaN,NaN,NaN,123,0.637306,UN Member States DO NOT criminalise conse...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
for colname in df.columns:
    df.rename(columns={colname : df[colname][1]}, inplace=True)

In [6]:
df = df.iloc[2:201].reset_index(drop=True)

In [7]:
df.drop(columns={'N', 'CN', 'CONTINENT'}, inplace=True)

In [8]:
df

,COUNTRY,Legal?,Gender/s,Years in Prison / Other,Constitutional,Broad Protections,Employment,Hate Crime / Aggr. Circs.,Incitement to Hatred / Violence,Ban on CTs,Marriage,Civil Unions,Joint Adoption,Second Parent Adoption
0,Algeria,NO,ANY GENDER,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Angola,YES,DOES NOT APPLY,DOES NOT APPLY,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
2,Benin,YES,DOES NOT APPLY,DOES NOT APPLY,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,Botswana,NO,ANY GENDER,7,NO,NO,YES,NO,NO,NO,NO,NO,NO,NO
4,Burkina Faso,YES,DOES NOT APPLY,DOES NOT APPLY,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Samoa,NO,MALE ONLY,7,NO,NO,YES,YES,NO,NO,NO,NO,NO,NO
195,Solomon Islands,NO,ANY GENDER,14,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
196,Tonga,NO,MALE ONLY,10,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
197,Tuvalu,NO,MALE ONLY,14,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
198,Vanuatu,YES,DOES NOT APPLY,DOES NOT APPLY,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO

In [9]:
df.rename(columns={'COUNTRY':'country', 'Legal?':'legal_male', 'Gender/s':'legal_female', 
                   'Years in Prison / Other':'prison_death', 'Constitutional':'cons_protect', 
                   'Broad Protections':'broad_protect', 'Employment':'employ_protect',
                   'Hate Crime / Aggr. Circs.':'crim_hate', 'Incitement to Hatred / Violence':'crim_incite',
                   'Ban on CTs':'ban_ct', 'Marriage':'marriage', 'Civil Unions':'unions', 'Joint Adoption':'j_adopt', 'Second Parent Adoption':'sec_adopt'},
                    inplace=True)

In [10]:
df = df[['country', 'legal_male', 'legal_female', 'prison_death', 'cons_protect',
              'broad_protect', 'employ_protect', 'crim_hate', 'crim_incite', 'ban_ct',
              'marriage', 'unions', 'j_adopt', 'sec_adopt']]

In [11]:
for colname in df.columns:
    print(colname)
    print(df[colname].unique())

country
['Algeria' 'Angola' 'Benin' 'Botswana' 'Burkina Faso' 'Burundi' 'Cameroon'
 'Cape Verde ' 'Central African Republic' 'Chad' 'Comoros' 'Congo'
 "CÃ´te d'Ivoire" 'DRC ' 'Djibouti' 'Egypt' 'Equatorial Guinea' 'Eritrea'
 'Eswatini' 'Ethiopia' 'Gabon' 'Gambia' 'Ghana' 'Guinea' 'Guinea-Bissau'
 'Kenya' 'Lesotho' 'Liberia' 'Libya' 'Madagascar' 'Malawi' 'Mali'
 'Mauritania' 'Mauritius' 'Morocco' 'Mozambique' 'Namibia' 'Niger'
 'Nigeria' 'Rwanda' 'SÃ£o Tome & Principe' 'Senegal' 'Seychelles'
 'Sierra Leone' 'Somalia' 'South Africa ' 'South Sudan' 'Sudan' 'Tanzania'
 'Togo' 'Tunisia' 'Uganda' 'Zambia' 'Zimbabwe' 'Antigua and Barbuda'
 'Argentina ' 'Bahamas ' 'Barbados' 'Belize' 'Bolivia' 'Brazil'
 'Costa Rica ' 'Chile ' 'Colombia ' 'Cuba ' 'Dominica'
 'Dominican Republic ' 'Ecuador ' 'El Salvador ' 'Grenada' 'Guatemala '
 'Guyana' 'Haiti ' 'Honduras ' 'Jamaica' 'Mexico ' 'Nicaragua ' 'Panama '
 'Paraguay' 'Peru ' 'St Kitts & Nevis' 'St Lucia'
 'St Vincent & the Grenadines' 'Suriname ' 'Trinidad and Tobago'
 'Uruguay ' 'Venezuela' 'Canada' 'United States' 'Afghanistan' 'Bahrain'
 'Bangladesh' 'Bhutan' 'Brunei Darussalam' 'Cambodia' 'China'
 'East Timor ' 'Palestine (1)' 'India' 'Indonesia (2)' 'Iraq' 'Iran'
 'Israel ' 'Japan ' 'Jordan ' 'Kazakhstan ' 'Kuwait' 'Kyrgyzstan ' 'Laos'
 'Lebanon' 'Macau' 'Malaysia' 'Maldives' 'Mongolia ' 'Myanmar' 'Nepal '
 'North Korea' 'Oman' 'Pakistan' 'Philippines' 'Qatar' 'Saudi Arabia'
 'Singapore' 'South Korea' 'Sri Lanka' 'Syria' 'Taiwan' 'Tajikistan '
 'Thailand ' 'Turkmenistan' 'Vietnam' 'United Arab Emirates' 'Uzbekistan'
 'Yemen' 'Albania ' 'Andorra ' 'Armenia ' 'Austria ' 'Azerbaijan '
 'Belarus ' 'Belgium ' 'Bosnia and Herzegovina' 'Bulgaria ' 'Croatia '
 'Cyprus ' 'Czechia' 'Denmark ' 'Estonia ' 'Finland ' 'France ' 'Georgia '
 'Germany ' 'Greece ' 'Hungary ' 'Iceland ' 'Ireland' 'Italy ' 'Kosovo '
 'Latvia ' 'Liechtenstein ' 'Lithuania ' 'Luxembourg ' 'Malta ' 'Moldova '
 'Monaco ' 'Montenegro ' 'Netherlands ' 'North Macedonia' 'Norway '
 'Poland ' 'Portugal ' 'Romania ' 'Russia' 'San Marino ' 'Serbia '
 'Slovakia ' 'Slovenia ' 'Spain' 'Sweden ' 'Switzerland ' 'Turkey '
 'Ukraine ' 'United Kingdom' 'Vatican City' 'Australia' 'Cook Islands'
 'Fiji ' 'Kiribati' 'Marshall Islands' 'Micronesia' 'New Zealand ' 'Nauru'
 'Palau ' 'Papua New Guinea' 'Samoa' 'Solomon Islands' 'Tonga' 'Tuvalu'
 'Vanuatu']
legal_male
['NO' 'YES' 'DE FACTO' 'Y ' 'Y' 'N']
legal_female
['ANY GENDER' 'DOES NOT APPLY' 'MALE ONLY' 'M ONLY']
prison_death
[2 'DOES NOT APPLY' 7 5 'UNDETERMINED' 3 14 1 'DEATH (NOT)' 'DEATH (REG)'
 10 'DEATH' 'FOR LIFE' 15 20 8]
cons_protect
['NO' 'YES' 'N' 'N ']
broad_protect
['NO' 'YES' 'N' 'N ' 'Y ']
employ_protect
['NO' 'YES' 'N ' 'Y']
crim_hate
['NO' 'YES' 'N ' 'Y ' 'N']
crim_incite
['NO' 'YES' 'N ' 'N']
ban_ct
['NO' 'YES' 'N ' 'N']
marriage
['NO' 'YES' 'N ' 'N']
unions
['NO' 'YES' 'N ' 'N']
j_adopt
['NO' 'YES' 'N ' 'N']
sec_adopt
['NO' 'YES' 'N ' 'N']

In [12]:
df['legal_female'].replace(to_replace='ANY GENDER', value=0, inplace=True)
df['legal_female'].replace(to_replace='MALE ONLY', value=1, inplace=True)
df['legal_female'].replace(to_replace='M ONLY', value=1, inplace=True)
df['legal_female'].replace(to_replace='DOES NOT APPLY', value=1, inplace=True)

In [13]:
df.replace(to_replace={2, 7, 5, 'UNDETERMINED', 3, 14, 'DEATH (NOT)', 'DEATH (REG)', 10, 'DEATH', 'FOR LIFE', 15, 20, 8}, value=1, inplace=True)
df.replace(to_replace='DOES NOT APPLY', value=0, inplace=True)

In [14]:
df.replace(to_replace='NO', value=0, inplace=True)
df.replace(to_replace='YES', value=1, inplace=True)
df.replace(to_replace='DE FACTO', value=0, inplace=True)
df.replace(to_replace='N', value=0, inplace=True)
df.replace(to_replace='Y', value=1, inplace=True)
df.replace(to_replace='N ', value=0, inplace=True)
df.replace(to_replace='Y ', value=1, inplace=True)

In [15]:
df

,country,legal_male,legal_female,prison_death,cons_protect,broad_protect,employ_protect,crim_hate,crim_incite,ban_ct,marriage,unions,j_adopt,sec_adopt
0,Algeria,0,0,1,0,0,0,0,0,0,0,0,0,0
1,Angola,1,1,0,0,1,1,1,1,0,0,0,0,0
2,Benin,1,1,0,0,0,0,0,0,0,0,0,0,0
3,Botswana,0,0,1,0,0,1,0,0,0,0,0,0,0
4,Burkina Faso,1,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Samoa,0,1,1,0,0,1,1,0,0,0,0,0,0
195,Solomon Islands,0,0,1,0,0,0,0,0,0,0,0,0,0
196,Tonga,0,1,1,0,0,0,0,0,0,0,0,0,0
197,Tuvalu,0,1,1,0,0,0,0,0,0,0,0,0,0
198,Vanuatu,1,1,0,0,0,0,0,0,0,0,0,0,0

In [16]:
for colname in df.columns:
    df['country'] = df['country'].str.strip()

In [17]:
for colname in df.columns:
    print(colname)
    print(df[colname].unique())

country
['Algeria' 'Angola' 'Benin' 'Botswana' 'Burkina Faso' 'Burundi' 'Cameroon'
 'Cape Verde' 'Central African Republic' 'Chad' 'Comoros' 'Congo'
 "CÃ´te d'Ivoire" 'DRC' 'Djibouti' 'Egypt' 'Equatorial Guinea' 'Eritrea'
 'Eswatini' 'Ethiopia' 'Gabon' 'Gambia' 'Ghana' 'Guinea' 'Guinea-Bissau'
 'Kenya' 'Lesotho' 'Liberia' 'Libya' 'Madagascar' 'Malawi' 'Mali'
 'Mauritania' 'Mauritius' 'Morocco' 'Mozambique' 'Namibia' 'Niger'
 'Nigeria' 'Rwanda' 'SÃ£o Tome & Principe' 'Senegal' 'Seychelles'
 'Sierra Leone' 'Somalia' 'South Africa' 'South Sudan' 'Sudan' 'Tanzania'
 'Togo' 'Tunisia' 'Uganda' 'Zambia' 'Zimbabwe' 'Antigua and Barbuda'
 'Argentina' 'Bahamas' 'Barbados' 'Belize' 'Bolivia' 'Brazil' 'Costa Rica'
 'Chile' 'Colombia' 'Cuba' 'Dominica' 'Dominican Republic' 'Ecuador'
 'El Salvador' 'Grenada' 'Guatemala' 'Guyana' 'Haiti' 'Honduras' 'Jamaica'
 'Mexico' 'Nicaragua' 'Panama' 'Paraguay' 'Peru' 'St Kitts & Nevis'
 'St Lucia' 'St Vincent & the Grenadines' 'Suriname' 'Trinidad and Tobago'
 'Uruguay' 'Venezuela' 'Canada' 'United States' 'Afghanistan' 'Bahrain'
 'Bangladesh' 'Bhutan' 'Brunei Darussalam' 'Cambodia' 'China' 'East Timor'
 'Palestine (1)' 'India' 'Indonesia (2)' 'Iraq' 'Iran' 'Israel' 'Japan'
 'Jordan' 'Kazakhstan' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Lebanon' 'Macau'
 'Malaysia' 'Maldives' 'Mongolia' 'Myanmar' 'Nepal' 'North Korea' 'Oman'
 'Pakistan' 'Philippines' 'Qatar' 'Saudi Arabia' 'Singapore' 'South Korea'
 'Sri Lanka' 'Syria' 'Taiwan' 'Tajikistan' 'Thailand' 'Turkmenistan'
 'Vietnam' 'United Arab Emirates' 'Uzbekistan' 'Yemen' 'Albania' 'Andorra'
 'Armenia' 'Austria' 'Azerbaijan' 'Belarus' 'Belgium'
 'Bosnia and Herzegovina' 'Bulgaria' 'Croatia' 'Cyprus' 'Czechia'
 'Denmark' 'Estonia' 'Finland' 'France' 'Georgia' 'Germany' 'Greece'
 'Hungary' 'Iceland' 'Ireland' 'Italy' 'Kosovo' 'Latvia' 'Liechtenstein'
 'Lithuania' 'Luxembourg' 'Malta' 'Moldova' 'Monaco' 'Montenegro'
 'Netherlands' 'North Macedonia' 'Norway' 'Poland' 'Portugal' 'Romania'
 'Russia' 'San Marino' 'Serbia' 'Slovakia' 'Slovenia' 'Spain' 'Sweden'
 'Switzerland' 'Turkey' 'Ukraine' 'United Kingdom' 'Vatican City'
 'Australia' 'Cook Islands' 'Fiji' 'Kiribati' 'Marshall Islands'
 'Micronesia' 'New Zealand' 'Nauru' 'Palau' 'Papua New Guinea' 'Samoa'
 'Solomon Islands' 'Tonga' 'Tuvalu' 'Vanuatu']
legal_male
[0 1]
legal_female
[0 1]
prison_death
[1 0]
cons_protect
[0 1]
broad_protect
[0 1]
employ_protect
[0 1]
crim_hate
[0 1]
crim_incite
[0 1]
ban_ct
[0 1]
marriage
[0 1]
unions
[0 1]
j_adopt
[0 1]
sec_adopt
[0 1]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         199 non-null    object
 1   legal_male      199 non-null    int64
 2   legal_female    199 non-null    int64
 3   prison_death    199 non-null    int64
 4   cons_protect    199 non-null    int64
 5   broad_protect   199 non-null    int64
 6   employ_protect  199 non-null    int64
 7   crim_hate       199 non-null    int64
 8   crim_incite     199 non-null    int64
 9   ban_ct          199 non-null    int64
 10  marriage        199 non-null    int64
 11  unions          199 non-null    int64
 12  j_adopt         199 non-null    int64
 13  sec_adopt       199 non-null    int64
dtypes: int64(13), object(1)
memory usage: 21.9+ KB